/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/raids` | `/raids`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/guilds` | `/guilds`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my_messages` | `/my_messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my_profile` | `/my_profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/raids` | `/raids`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/guilds` | `/guilds`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my_messages` | `/my_messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my_profile` | `/my_profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/raids${`?${string}` | `#${string}` | ''}` | `/raids${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/guilds${`?${string}` | `#${string}` | ''}` | `/guilds${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my_messages${`?${string}` | `#${string}` | ''}` | `/my_messages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my_profile${`?${string}` | `#${string}` | ''}` | `/my_profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/raids` | `/raids`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/guilds` | `/guilds`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my_messages` | `/my_messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my_profile` | `/my_profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
